### ISSUE TITLE
Create the database model for the `SERVICE` relation

### ISSUE THREAD

**Issue by gridhead** [fedora-infra/webhook-to-fedora-messaging#11]
Please refer to https://fedora-arc.readthedocs.io/en/latest/webhook2fedmsg/dber.html#service for more information.

**Comment by abompard** [comment]
I'm not sure I understand what sort of data you expect this table to hold. Do you have a couple examples? Is it, for example, Github repos ? What would be in `topic`? What would be in `msg_head`/`msg_body` (now `story`)?
