### ISSUE TITLE
Add a default LICENSE.txt to the root directory

### ISSUE THREAD

**Issue by jwflory** [fedora-infra/webhook-to-fedora-messaging#82]
Without a `LICENSE.txt` in the root level of the repository, license detection fails because the licenses are kept in a non-conventional place. Since there is only one license used in this project, please move the license to the root level of the repo and rename the file as `LICENSE.txt`.

This will trigger the GitHub Licenses API and make it easier for Fedora to comply with its Freedom Foundation.

**Comment by abompard** [comment]
I've added a symlink to the file in `LICENSES`, which we must keep to be compliant with the [FSF Reuse spec](https://reuse.software/). It seems to be recognized by Github's license detection.
